import {
  getFollowerProfile,
  getIsFollowing,
  getPlaylistAudios,
  getUserFollowers,
  getUserFollowings,
} from './../controllers/profileController';
import {
  getAutoGeneratedPlaylist,
  getPublicPlaylist,
  getPublicProfile,
  getPublicUploads,
  getUploads,
  updateFollower,
} from '@/controllers/profileController';
import {authUser} from '@/middleware/auth';
import {Router} from 'express';

const router = Router();

router.post('/follower/:profileId', authUser, updateFollower);
router.get('/uploads', authUser, getUploads);
router.get('/uploads/:profileid', getPublicUploads);
router.get('/info/:profileId', getPublicProfile);
router.get('/playlist/:profileid', getPublicPlaylist);
router.get('/auto-generated-playlist', authUser, getAutoGeneratedPlaylist);
router.get('/followers', authUser, getUserFollowers);
router.get('/followings', authUser, getUserFollowings);
router.get('/followers/:profileid', authUser, getFollowerProfile);
router.get('/playlist-audios/:playlistid', getPlaylistAudios);
router.get('/is-following/:profileid', authUser, getIsFollowing);

export default router;
