import Audio from '@/models/audioModel';
import AutoGeneratedPlaylist from '@/models/autoGeneratedPlaylistModel';
import cron from 'node-cron';

const autoGeneratedPlayList = async () => {
  const result = await Audio.aggregate([
    {$sort: {likes: -1}},
    {$sample: {size: 20}},
    {
      $group: {
        _id: '$category',
        audios: {$push: '$$ROOT._id'},
      },
    },
  ]);

  result.map(async item => {
    await AutoGeneratedPlaylist.updateOne(
      {title: item._id},
      {$set: {items: item.audios}},
      {upsert: true},
    );
  });
};

cron.schedule('0 0/5 * * * ', async () => {
  await autoGeneratedPlayList();
});
